### ISSUE TITLE
Erro no material de Delta encoding

### ISSUE THREAD

**Issue by MaxwellOliveira01** [UnBalloon/programacao-competitiva#2]
Estava lendo o material de Delta encoding e, no codigo final, creio que a linha destacada deveria ser  += e não = 
![image](https://user-images.githubusercontent.com/71512334/93611298-859f8c00-f9a4-11ea-827f-eefb640b7da0.png)

**Comment by joseleite19** [comment]
O vetor `v`  está inicializado com 0 então `+=` e `=` têm o mesmo resultado.
